### ISSUE TITLE
[BUG] Mastodon on iOS will not let the phone auto-lock

### ISSUE THREAD

**Issue by costumrobo** [mastodon/mastodon-ios#1371] opened 2024-12-03 15:57 UTC
### Is there an existing issue for this?

- [x] I have searched the issues (both open and closed)

### Current Behavior

When I am using Mastodon on my iPhone 15 Pro, after I am done scrolling, even when there is no media being played, the app prevents the phone from auto-locking

### Expected Behavior

After 1 minute of idle, the screen should shut off and lock

### Environment

```markdown
- Device: iPhone 15 Pro
- OS: iOS 18.2
- Version: 2024.11
- Build: 6903
```

**Comment by jayantpatil** [comment] 2024-12-04 16:28
@costumrobo Could you share what's auto-lock timer set to on your device?
In Settings->Display & brightness -> Auto-Lock?

**Comment by costumrobo** [comment] 2024-12-05 17:00
> [@costumrobo](https://github.com/costumrobo) Could you share what's auto-lock timer set to on your device? In Settings->Display & brightness -> Auto-Lock?

I have it set to 1-minute

**Comment by whattherestimefor** [comment] 2024-12-06 21:23
Duplicate of https://github.com/mastodon/mastodon-ios/issues/545

**Closed as completed by whattherestimefor** 2024-12-06 21:23 UTC
Labels: Bug, Needs Triage
