### ISSUE TITLE
[BUG] Total percentage of wrong votes in polls

### ISSUE THREAD

**Issue by julienducos** [mastodon/mastodon-ios#1091] opened 2023-07-05 13:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Percentage vote totals are wrong on some polls (see: https://1password.social/@1password/110655764923003398 on the app -> correct on the website)

### Expected Behavior

100%

### Steps To Reproduce

Open the app on a survey result (see example)

### Environment

```markdown
- Device:iPhone 14 Pro
- OS:iOS 16.5.1 stable
- Version:2023.11
- Build:337
```

### Anything else?

.

**Comment by grahhnt** [comment] 2023-08-14 19:09
![IMG_1307](https://github.com/mastodon/mastodon-ios/assets/46821216/9763e438-5576-4ae5-bd62-9d5fe204a896)

looks like a partial caching issue?

when I voted on this poll I was the first person to cast a vote

**Comment by GCaw** [comment] 2023-09-08 18:11
I've observed similar behaviour.
Is this a duplicate/related to #966

**Comment by zeitschlag** [comment] 2023-11-04 09:07
@GCaw Most probably, yes. Thank you!

**Comment by zeitschlag** [comment] 2023-11-04 09:07
Duplicate of #966

**Closed as not planned by zeitschlag** 2023-11-04 09:07 UTC
