### ISSUE TITLE
[BUG] Share sheet failure - “no account available”

### ISSUE THREAD

**Issue by TS6ix2GaH3q679h5** [mastodon/mastodon-ios#1176] opened 2023-11-23 02:42 UTC
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

When sharing text or link to Mastodon app via iOS share sheet, returns posting box but says “no account available” and cannot proceed. 

This, despite being logged in on the app. Tried logout, uninstalled, still not working. App itself working fine. 

### Expected Behavior

Should let me share/post the shared content 

### Steps To Reproduce

1. Highlight some text
2. Hold down on it
3. “Share…” from iOS pop up
4. Choose Mastodon app
5. “No account” pop up

### Environment

```markdown
- Device: iPhone
- OS: 16
- Version: 2023.15
- Build: 6005
```

**Comment by TS6ix2GaH3q679h5** [comment] 2023-11-23 02:47
FYI another user experiencing the same:

> Thanks for the Mastodon App updates, but since then the iOS share sheet isn’t working. When I try to share a webpage to my account I’m shown a page that says ‘No available account’ This I broken on both my iPhone and iPad running iOS 17.1.1 #mastodon #mastodonsupport #mastodonapp #mastodonios

https://mas.to/@barstep/111420359247223133

**Comment by zeitschlag** [comment] 2023-11-23 06:26
Duplicate of #1168 

Seems to me, that you didn’t search the issues 😉

**Closed as not planned by zeitschlag** 2023-11-23 06:26 UTC
Labels: Bug

**Comment by TS6ix2GaH3q679h5** [comment] 2023-11-24 01:54
> Duplicate of #1168
> 
> Seems to me, that you didn’t search the issues 😉

Ah ha, sorry! I searched ""no account available" and saw no open bug reports. Turns out it was closed 4 days ago. Oops. Anyway glad it will be addressed. Thanks guys.
