### ISSUE TITLE
[BUG] 2023.14 crashes immediately 

### ISSUE THREAD

**Issue by rstieger** [mastodon/mastodon-ios#1162] opened 2023-11-15 15:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since updating to 2023.14, the Mastodon app crashes immediately. 

### Expected Behavior

App opens

### Steps To Reproduce

1. Click app icon to open
2. Black screen for fraction of a second then terminates

### Environment

```markdown
- Device:iPhone 13
- OS: iOS 16.6.1
- Version: 2023.14
- Build:
```

**Comment by zeitschlag** [comment] 2023-11-15 15:37
Duplicate of #1160

@rstieger Thanks for reporting it. We're aware of that, you basically have the following options:

- Wait for a few hours until Apple approves our update
- Update to iOS 17

Thanks!

**Closed as not planned by zeitschlag** 2023-11-15 15:37 UTC
