### ISSUE TITLE
app crash on opening 

### ISSUE THREAD

**Issue by TamirRothschild** [mastodon/mastodon-ios#1164] opened 2023-11-15 16:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i open the app its immediately crashing and closes the app

### Expected Behavior

the should open as it did before, all i change was 15 nov update 

### Steps To Reproduce

update to the 15 nov update 
open the app

### Environment

```markdown
- Device:iphone14
- OS:ios
- Version:16.5.1
- Build:2023.14
```

**Comment by zeitschlag** [comment] 2023-11-15 16:37
Duplicate of #1160

@TamirRothschild Another person who didn't search the issues ;) Thanks for reporting it. We're aware of that, you basically have the following options:

- Wait for a few hours until Apple approves our update (it's in review right now)
- Update to iOS 17

Thanks!

**Closed as not planned by zeitschlag** 2023-11-15 16:37 UTC

**Comment by TamirRothschild** [comment] 2023-11-15 16:49
ok thank you very much, i looked at the issues it said the last one was from a day ago and the update went live 19 hours ago, but thank you for the very fast response
