### ISSUE TITLE
Cannot download videos

### ISSUE THREAD

**Issue by sallyFoster** [mastodon/mastodon-ios#1186] opened 2023-11-29 02:10 UTC
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

Videos are not being downloaded

### Expected Behavior

Videos should be downloaded

### Steps To Reproduce

1. Long tap on a video
2. Tap on Save Photo

### Environment

```markdown
- Device: iPhone 11 Pro Max
- OS: iOS 17.1
```

### Anything else?

**Comment by zeitschlag** [comment] 2023-11-29 06:16
Duplicate of #1068

**Closed as not planned by zeitschlag** 2023-11-29 06:16 UTC
