### ISSUE TITLE
Mastodon iOS App server search issue

### ISSUE THREAD

**Issue by AquaBat** [mastodon/mastodon-ios#1108] opened 2023-08-22 02:06 UTC
### Steps to reproduce the problem

1. go to server search within Mastodon app [on iOS]
2. type in “misskey.io”
3. search recognizes misskey.io, allows it to be selected
4. tap “Next”

### Expected behaviour

After selecting misskey.io, the app should have continued to a login screen allowing user to log in to a misskey account

### Actual behaviour

Error popup saying “Not Found” occurs, does not move to login screen

### Detailed description

When trying to select misskey.io as a server to log into an account on, the server search brings it up as selectable, but when trying to move on to logging in by tapping “next”, after a second or two of loading it simply pops up an error message saying “Not Found”. It WAS clearly found, otherwise it wouldn’t be recommending it as a positive search result. It simply refuses to allow login to misskey.io, and I am unable to determine why.

### Mastodon instance

misskey.io (within app’s server search)

### Mastodon version

Mastodon for iOS v2023.11 (337)

**Comment by ClearlyClaire** [comment] 2023-08-22 07:06
Hi! Bugs in the iOS app should be filed to https://github.com/mastodon/mastodon-ios!

**Comment by renchap** [comment] 2023-08-22 08:33
Moved to the correct repo

**Comment by zeitschlag** [comment] 2023-08-22 09:18
Hi @AquaBat, thank you for this report. I just fired up the app and was able to reproduce the issue. But: It's not a bug nor an issue of the iOS-app. misskey doesn't implement the [Mastodon-API](https://docs.joinmastodon.org/api/guidelines/) that is used by the Mastodon-apps, but [brings its own](https://misskey-hub.net/en/docs/api/). In other words: You're using the wrong app :) That's why I'll close this issue.

Regarding the alert: When you press "Next" after entering the instance in that textfield, the app tries to create an app on your instance by sending a `POST`-request to [`/api/v1/apps`](https://docs.joinmastodon.org/methods/apps/#create). And this endpoint doesn't exist on [misskey.io](https://misskey.io/api/v1/apps), that's why you get that "Not Found"-alert.

**Closed as not planned by zeitschlag** 2023-08-22 09:18 UTC
