### ISSUE TITLE
[FEATURE REQUEST] Render display cards for links in app timeline

### ISSUE THREAD

**Issue by DanaEpp** [mastodon/mastodon-ios#518] opened 2022-11-06 19:53 UTC
Most social apps have the ability to pre-fetch a URL and render a display card from markdown/metadata. This provides a richer experience as it allows a user to understand what is at the link and provides better visual cues to the information being linked to.

Twitter has [documented its implementation quite well here](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards). 

It seems Mastodon web client sorta renders it, but not very well. The IOS app doesn't even attempt to render a card.

My request would be to follow the same formatting as other social apps. I know for [my blog](https://danaepp.com), they all render out the card for my posts quite well, but differently. ie, Some render extra metadata, while others do not. Twitter will show the card image, title, and description... where LinkedIn also renders how long the read would be for the article.

I'll link a few examples to show the difference.  

- [Twitter card](https://infosec.exchange/system/media_attachments/files/109/298/495/238/334/202/original/a7c968182757c17c.jpg)
- [LinkedIn card](https://infosec.exchange/system/media_attachments/files/109/298/490/008/285/547/original/95483e987fcc971a.jpg)

**Comment by jmeosbn** [comment] 2022-11-22 15:46
Is this a temporary issue with the underlying API or SDK (given https://github.com/mastodon/mastodon/issues/19898)?

Some authors will simply post a link to an article; which seems lazy, but if they’re expecting the timeline to show a link preview with the article title and image, then it makes sense not to repeat that.

![7F856EDC-5F6A-4BD6-85C2-3FF93FE837B7](https://user-images.githubusercontent.com/530912/203357964-cca650a5-6c94-4ee3-b4fe-dc750fa83923.jpeg)

Unfortunately, this all falls over when there is no preview:

![3F1C7DA2-95CA-401F-B21A-57A56C41AC39](https://user-images.githubusercontent.com/530912/203357866-e10a3017-1b29-41de-9e0f-8a420b93f2a8.jpeg)

It seems unfair to complain to the author when there’s no issue depending on the client.

My own posts (to other’s articles) on Twitter usually include a snippet of text, so omit the title to save space (since it’s normally previewed). I’ve kept this style on Mastodon and have missed the link preview that gives context to the quoted text/comment.

**Comment by j-f1** [comment] 2022-11-22 21:50
Duplicate of #234.

**Closed** 2022-12-15 13:28 UTC
