### ISSUE TITLE
App showing my server as offline in the home feed while on the web it is online.

### ISSUE THREAD

**Issue by sallyFoster** [mastodon/mastodon-ios#1173] opened 2023-11-19 19:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The app is showing my server is offline while on the web it works fine.

![IMG_9984](https://github.com/mastodon/mastodon-ios/assets/104597302/03bcaa0d-2779-4b98-9ed6-55f71f58aae4)

URL: https://toots.matapacos.dog/

### Expected Behavior

The server should load fine on the app.

### Steps To Reproduce

1. Create an account on https://toots.matapacos.dog/

2. Try to load your home feed

### Environment

```markdown
- Device: iPhone 11 Pro Max
- OS: iOS 17.1
- Version:
- Build:
```

### Anything else?

It is only showing the home feed as offline. If I click the search/explore button, the window doesn’t say “offline” in the top

**Comment by zeitschlag** [comment] 2023-11-20 07:32
Duplicate of #898

**Closed as not planned by zeitschlag** 2023-11-20 07:32 UTC
