### ISSUE TITLE
[Feature]: switch between icon

### ISSUE THREAD

**Issue by AugustinMauroy** [mastodon/mastodon-ios#1298] opened 2024-05-20 20:34 UTC
### Description

Having possibility to chose which icon we want on our phone. Such as Github.

### Suggested Solution

- Having setting for that using list of icon
- We should found multiple icon to provide. (why not one mastodon with rainbow)

**Comment by zeitschlag** [comment] 2024-05-20 20:37
Duplicate of #339

**Closed as not planned by zeitschlag** 2024-05-20 20:37 UTC
