### ISSUE TITLE
[BUG] <freezes after 100 char typed>

### ISSUE THREAD

**Issue by Pierre-Alexandre-Gourdain** [mastodon/mastodon-ios#894] opened 2023-01-19 00:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

after writing 100 character or so the app freezes. We have a limit of 5000 character on the server. The web interface works fine.

### Expected Behavior

Not freezing

### Steps To Reproduce

while typing a toot

### Environment

```markdown
- Device:iPhone SE
- OS:15.6.1
- Version:
- Build:
```

### Anything else?

Yes. The limit is 5000 on the server but only 500 is allowed in the app!

**Comment by j-f1** [comment] 2023-01-19 00:31
Duplicate of #705.

**Comment by Pierre-Alexandre-Gourdain** [comment] 2023-01-19 13:36
Duplicate of 705

**Closed as completed** 2023-01-19 13:36 UTC
