### ISSUE TITLE
[BUG] App crashes when editing info on profile

### ISSUE THREAD

**Issue by strifeSpec** [mastodon/mastodon-ios#635] opened 2022-11-18 19:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

App crashes within a second of clicking "Edit info" button on profile.

### Expected Behavior

Allowing user to edit the info on their profile

### Steps To Reproduce

1. Open app
2. Go to profile
3. Click "Edit info"

### Environment

```markdown
- Device: iPhone 12 Pro Max
- OS: iOS 15.6.1
- Version: 1.4.5
- Build: 144
```

### Anything else?

This has been happening for several months. Have signed out and reinstalled app several times and the issue persists.

**Comment by tejuamirthi** [comment] 2022-11-18 19:44
Hey I have used the same exact version of the application and it works just fine. 
Can you please share a recording of the crash or any other info?
Version - 1.4.5 
Build - 144 
iOS - 15.6.1

**Comment by j-f1** [comment] 2022-11-18 19:45
Can you go to Settings → Privacy → Analytics & Improvements → Analytics Data and upload the most recent `Mastodon-*.ips` file so that we can get more info about exactly what’s causing the crash? (You might need to send the file to a computer and rename it to .txt or copy+paste the content into a code block to get it to upload to GitHub)

**Comment by strifeSpec** [comment] 2022-11-18 20:22
> Can you go to Settings → Privacy → Analytics & Improvements → Analytics Data and upload the most recent `Mastodon-*.ips` file so that we can get more info about exactly what’s causing the crash? (You might need to send the file to a computer and rename it to .txt or copy+paste the content into a code block to get it to upload to GitHub)

Ahh sorry, I just updated my phone to iOS 16 a few minutes ago! I just realised my phone was out of date. Though, the app stopped crashing after I updated.

**Comment by j-f1** [comment] 2022-11-19 00:35
That’s great!

**Comment by Skawtnyc** [comment] 2022-11-20 14:44
Still happening in the new iOS app on my iPad, running iPadOS 16.1.1. I get a brief flicker of the profile editing page before the app just completely shuts down. I’ve attached the file you asked for.
[Mastodon-2022-11-20-094156.zip](https://github.com/mastodon/mastodon-ios/files/10049940/Mastodon-2022-11-20-094156.zip)

**Comment by j-f1** [comment] 2022-11-20 16:57
Ok, thanks for the info! It looks like the underlying issue here is that a collection view (maybe the one on the profile page?) is stuck in a recursive update loop, which it detects and then crashes as a result. I’m not sure why that’s happening but maybe it can help someone debug?

**Comment by zeitschlag** [comment] 2022-11-21 06:05
Looks like a duplicate of #413 to me

**Closed by zeitschlag** 2022-11-21 06:05 UTC
Labels: duplicate
