### ISSUE TITLE
“reblogged” should be “boosted”

### ISSUE THREAD

**Issue by Scenario** [mastodon/mastodon-ios#768] opened 2022-12-13 22:26 UTC
### Steps to reproduce the problem

Look at your timeline where people have boosted posts.

### Expected behaviour

soandso boosted

### Actual behaviour

sosandso reblogged

### Detailed description

Blogged and Reblogged are really stupid verbs. Mastodon is not a blogging site. On a blog site, commenters can’t reblog you on that same site. They can only comment in situ. What’s really happening here is that when people think you said something worthy, they can boost your voice. So that should be the verb.

### Specifications

Latest iOS app

**Comment by todoneunl** [comment] 2022-12-13 22:35
Agreed, but wrong repository. See https://github.com/mastodon/mastodon-ios

**Comment by j-f1** [comment] 2022-12-14 00:25
Duplicate of https://github.com/mastodon/mastodon-ios/issues/632

**Comment by Gargron** [comment] 2022-12-14 00:30
Reblogging is the proper term and Mastodon is a microblogging platform.

**Closed as not planned by Gargron** 2022-12-14 00:30 UTC

**Comment by todoneunl** [comment] 2022-12-14 00:52
> Reblogging is the proper term and Mastodon is a microblogging platform.

The latter is true. But in the web-app it is and always has been named _boosted_, and people are used to that. It's a bad idea to have different names of features on different devices, that will confuse people.
