### ISSUE TITLE
[BUG] App crashes on startup

### ISSUE THREAD

**Issue by larsimmisch** [mastodon/mastodon-ios#1163] opened 2023-11-15 16:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On startup, the app crashes immediately.

### Expected Behavior

The app starts and shows the UI

### Steps To Reproduce

On my Phone, Mastodon crashes immediately after start, before even the splash screen is shown.

The console does not show much, but here s what I get:

```
error	16:58:58.250453+0100	SpringBoard	[application<org.joinmastodon.app>:33506] Workspace afterlife assertion failed: Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}
error	16:58:58.321841+0100	SpringBoard	Scene FBSceneManager/sceneID:org.joinmastodon.app-default update failed: <NSError: 0x28169f720; domain: FBSceneErrorDomain; code: 1 (operation-failed); reason: "Scene update failed."> {
    NSUnderlyingError = <NSError: 0x2814828e0; domain: FBWorkspaceScene; code: 1; reason: "Client process exited.">;
}
error	16:58:58.326028+0100	SpringBoard	Scene FBSceneManager/sceneID:org.joinmastodon.app-default update failed: <NSError: 0x281672d90; domain: FBSceneErrorDomain; code: 1 (operation-failed); reason: "Scene update failed."> {
    NSUnderlyingError = <NSError: 0x281480390; domain: FBWorkspaceScene; code: 1; reason: "Client process exited.">;
}
error	16:58:58.378590+0100	symptomsd	COSMCtrl _foregroundAppActivity incoming bundle org.joinmastodon.app has nil supplied UUID, no existing entries so skip
error	16:58:58.389169+0100	symptomsd	COSMCtrl _foregroundAppActivity incoming bundle org.joinmastodon.app has nil supplied UUID, no existing entries so skip
```

### Environment

```markdown
- Device: iPhone 14
- OS: 16.7.2
- Version: Latest from AppStore (can't check because app doesn't start)
- Build: Latest from AppStore (can't check because app doesn't start
```

**Comment by zeitschlag** [comment] 2023-11-15 16:08
Duplicate of #1160

@larsimmisch Thanks for reporting it. We're aware of that, you basically have the following options:

- Wait for a few hours until Apple approves our update
- Update to iOS 17

Thanks!

**Closed as not planned by zeitschlag** 2023-11-15 16:08 UTC

**Comment by larsimmisch** [comment] 2023-11-15 16:10
Thanks!
