### ISSUE TITLE
[Feature]: Option to collapse long posts in timeline

### ISSUE THREAD

**Issue by jlnprssnr** [mastodon/mastodon-ios#1191] opened 2023-12-04 10:10 UTC
### Description

The official app needs an option to collapse long posts in the timeline, currently they always show fully. Which is especially unintuitive when reading from old to new and scrolling up.

### Suggested Solution

Either define a usable hard coded post length, or let us set set our own character limit.

**Comment by zeitschlag** [comment] 2023-12-19 14:56
Duplicate of #730

**Closed as not planned by zeitschlag** 2023-12-19 14:56 UTC
