### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Peppersqueaks** [mastodon/mastodon-ios#1057] opened 2023-06-04 11:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am unable to add any media to posts, and when I try the app freezes and I have to manually close the app. Is there a privacy setting that needs changed or other? Thank you

### Environment

```markdown
- Device:
- OS:
- Version:
- Build:
```

**Comment by zeitschlag** [comment] 2023-08-25 12:59
Duplicate of #965

**Closed as not planned by zeitschlag** 2023-08-25 12:59 UTC
