### ISSUE TITLE
[BUG] Cannot upload profile picture

### ISSUE THREAD

**Issue by koyuawsmbrtn** [mastodon/mastodon-ios#1291] opened 2024-05-14 10:42 UTC
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

Selecting a new profile picture from gallery or taking a picture doesn’t do anything. The profile picture stays the same. Other apps don’t have that issue so I can confirm it’s not a server-side bug.

### Expected Behavior

The profile picture uploads and can be applied.

### Steps To Reproduce

1. Open the Mastodon app
2. Tap your profile
3. Tap "Edit profile"
4. Choose a profile picture from the gallery or take one with your camera
5. Poof. Nothing happens.

### Environment

```markdown
- Device: iPhone 13 (base model)
- OS: iOS 17.4.1
- Version: latest, App Store
- Build: latest
```

**Comment by zeitschlag** [comment] 2024-05-14 10:44
Duplicate of #1276

**Closed as not planned by zeitschlag** 2024-05-14 10:44 UTC
