### ISSUE TITLE
[BUG] Filtered message placeholder consumes entire viewport height

### ISSUE THREAD

**Issue by marians** [mastodon/mastodon-ios#358] opened 2022-04-06 10:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As shown in the screenshot, a filtered message is consuming the entire height of my timeline viewport.

### Expected Behavior

The consumed height should only be enough to accomodate the "Filtered" message plus some padding.

### Steps To Reproduce

1. Create a message filter.
2. Load the app.
3. Find a filtered message.

### Environment

```markdown
- Device: iPhone 6s
- OS: 15.4.1
- Version: 1.3.0
- Build: 109
```

### Anything else?

<details>
<summary>Screenshot (de_DE localized)</summary>

![IMG_0422](https://user-images.githubusercontent.com/273727/161951847-663966e8-2ad6-40ef-bbcf-e77f2c1546bd.PNG)

</details>

**Comment by marians** [comment] 2022-08-09 13:42
Just an update that this is still occurring and it is annoying. Sometimes I have to scroll several pages in order to get past a bunch of filtered messages. Even a single message can consume multiple times a viewport's height.

**Comment by whattherestimefor** [comment] 2024-11-08 17:07
Duplicate of #441

**Closed** 2024-11-12 14:07 UTC
