### ISSUE TITLE
[BUG] Truncated option text make poll unusable

### ISSUE THREAD

**Issue by agateblue** [mastodon/mastodon-ios#1040] opened 2023-05-09 07:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When viewing a poll such as https://eldritch.cafe/@UnePorte/110326114595828458 on the Iphone app, the poll options text is truncated. This makes it impossible to understand the option and answer.

![image](https://user-images.githubusercontent.com/1970915/237030374-ee58d260-a72c-4e8a-b281-b879742b415b.png)

### Expected Behavior

The text is displayed in full.

### Steps To Reproduce

1. Create a poll with multiple options and long text for each option or load an existing one such as with the link I provided
2. See that the options are truncated and unreadable

### Environment

```markdown
I'm opening this issue on behalf of another user, so I don't have this info.

- Device:
- OS:
- Version:
- Build:
```

**Comment by j-f1** [comment] 2023-05-09 11:31
Duplicate of #291.

**Closed as not planned** 2023-05-10 20:47 UTC
