### ISSUE TITLE
[BUG] <Layout issue with iPad OS - Side panel is cut off on the right>

### ISSUE THREAD

**Issue by tipyn** [mastodon/mastodon-ios#1141] opened 2023-11-02 20:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![IMG_0019](https://github.com/mastodon/mastodon-ios/assets/6654258/c2dd8757-325c-4291-bc3a-5b9df4fa05c1)

### Expected Behavior

Side panel is correctly wrapped.

### Environment

```markdown
- Device: iPad Pro 12 inch - 5th Gen
- OS: iPad OS
- Version: 17
- Build: 1
```

**Comment by zeitschlag** [comment] 2023-11-04 09:04
Duplicate of #1090 et al.

**Closed as not planned by zeitschlag** 2023-11-04 09:04 UTC
