### ISSUE TITLE
[Feature]: Display follow and followed button differently

### ISSUE THREAD

**Issue by Wulfheart** [mastodon/mastodon-ios#1112] opened 2023-08-29 06:56 UTC
### Description

https://github.com/mastodon/mastodon-ios/assets/25671390/40910a28-9bc5-4ad9-bbaa-0962ddda48c3

When following an account the follow button stays the same. I don’t get a visual hint that I am subscribed to it. 

### Suggested Solution

I would much prefer a solution like Twitter or Instagram where the button color changes after you followed. 

Instagram:

https://github.com/mastodon/mastodon-ios/assets/25671390/37650f43-bb41-4e8f-8a32-95bba60483aa

Twitter:

https://github.com/mastodon/mastodon-ios/assets/25671390/97370afa-bd6d-49c3-aaac-c4eeb4332061

**Comment by zeitschlag** [comment] 2023-09-18 08:55
Duplicate of #229

**Closed as not planned by zeitschlag** 2023-09-18 08:55 UTC
