### ISSUE TITLE
[BUG] Crash after deletion

### ISSUE THREAD

**Issue by SinghDominik** [mastodon/mastodon-ios#939] opened 2023-02-11 23:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I delete a toot and create a new one, Mastodon will crash.

### Steps To Reproduce

1. Delete a toot
2. create a new one

### Environment

```markdown
- Device: iPhone 14
- OS: iOS
- Version: 16.3
```

**Comment by zeitschlag** [comment] 2023-02-20 19:57
(Most probably) a duplicate of #940

**Closed as not planned by zeitschlag** 2023-02-20 19:57 UTC
