### ISSUE TITLE
App is crashing when writing posts on iPhone

### ISSUE THREAD

**Issue by WhereCanI** [mastodon/mastodon-ios#940] opened 2023-02-12 19:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you are writing a new update-adding a post in the iOS app, it will crash once you have written approx. 100-150 characters. First the app gets stuck and then it crashes. 

### Steps To Reproduce

1. Add a new post in the app.
2. Write a story, and once you reach 100-150 characters the app will get stuck and eventually crash.

### Environment

```markdown
- Device: iPhone SE2
- OS: 16.3
- Version:
- Build:
```

**Comment by j-f1** [comment] 2023-02-12 19:36
Duplicate of https://github.com/mastodon/mastodon-ios/issues/705 — I’ve never been able to reproduce this myself so I haven’t been able to find a real fix but I did open https://github.com/mastodon/mastodon-ios/pull/932 in an attempt to make the issue less severe.

**Comment by SinghDominik** [comment] 2023-02-14 15:36
I don't know if it is really a duplicate as it literally crashs instead of just hang. And it has nothing to do with an amount of chars because it happens at all char amount ranges.

**Comment by SinghDominik** [comment] 2023-02-14 15:36
> Duplicate of #705 — I’ve never been able to reproduce this myself so I haven’t been able to find a real fix but I did open #932 in an attempt to make the issue less severe.

I don't know if it is really a duplicate as it literally crashs instead of just hanging. And it has nothing to do with an amount of chars because it happens at all char amount ranges.

**Closed as completed** 2023-02-25 18:34 UTC
