### ISSUE TITLE
[Feature]: iOS 18 - Adaptive icon

### ISSUE THREAD

**Issue by upintheairsheep** [mastodon/mastodon-ios#1322] opened 2024-06-26 22:01 UTC
### Description

Hello, iOS 18 introduced new icon styles, please make the mastodon icon an adaptive icon. It is better to do it before launch.

### Suggested Solution

N/A, just add a new adaptive icon.

**Comment by samhenrigold** [comment] 2024-07-31 12:56
This is easy to do, but we need to wait until Apple begins accepting iOS 18 binaries to the App Store. That normally happens when the release candidate is released about a week before public availability.

**Comment by lumaa-dev** [comment] 2024-08-01 21:31
> we need to wait until Apple begins accepting iOS 18 binaries to the App Store.

Optionally, they could make a iOS 18 branch and wait this fall before uploading the iOS 18 branch to the App Store

**Comment by fizwidget** [comment] 2024-09-17 09:13
Is this still being worked on? iOS 18 has now been released, and Mastodon is the only app on my homescreen without an adaptive icon. It stands out a bit 😅

**Comment by Adafede** [comment] 2024-10-07 18:28
> Is this still being worked on? iOS 18 has now been released, and Mastodon is the only app on my homescreen without an adaptive icon. It stands out a bit 😅

True. Would be great to have an adaptative icon!

**Comment by kimar** [comment] 2024-10-08 06:47
Yes this is being worked on and an update will be released soon.

**Comment by fizwidget** [comment] 2024-10-23 20:36
Thanks for the update, it looks much better now! 🙂

Although, it still looks a bit inconsistent with the other icons in my phone. Example:
![Image](https://github.com/user-attachments/assets/7fb14252-a7bd-4bd7-8eb8-d593527cd15a)

The icon’s inner parts have turned white rather than dark. Was this by design or by accident?

**Closed as completed** 2024-11-21 02:02 UTC
