### ISSUE TITLE
Switching tabs now reloads my home feed and I lose my place 

### ISSUE THREAD

**Issue by daedhir** [mastodon/mastodon-ios#749] opened 2022-12-11 04:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

New iOS app update now reloads and scrolls me to the top of home when I switch tabs.

### Expected Behavior

Home should keep my place until I explicitly scroll to the top 

### Steps To Reproduce

Always reproduces

### Environment

```markdown
- Device:iPhone 14 Pro Max
- OS: iOS 
- Version: 
- Build:
```

**Comment by j-f1** [comment] 2022-12-11 12:21
Duplicate of #744

**Closed as completed** 2022-12-11 16:23 UTC
