### ISSUE TITLE
[BUG] UI: Sidebar does not properly show ful profile

### ISSUE THREAD

**Issue by jvacek** [mastodon/mastodon-ios#670] opened 2022-11-21 22:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The sidebar has some content overflow issues when viewing a profile

### Expected Behavior

No overflow issues in the sidebar when viewing profiles

### Steps To Reproduce

- Ensure the app is wide enough ti display sidebar
- Search for a profile, or open one from your timeline
- See that the content is underflowing the edge of the window

### Environment

```markdown
- Device: M1 MBP 13"
- OS: macOS 13
- Version: 1.4.7
- Build: 199
```

### Anything else?

<img width="290" alt="image" src="https://user-images.githubusercontent.com/1302278/203173156-40b91bbc-3c30-422e-b400-359063c69c5f.png">

**Comment by zeitschlag** [comment] 2022-11-22 07:21
Duplicate of #657

**Closed as completed by zeitschlag** 2022-11-22 07:21 UTC
