### ISSUE TITLE
Toot lost in poor network conditions

### ISSUE THREAD

**Issue by foolip** [mastodon/mastodon-ios#846] opened 2023-01-01 07:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I composed a toot in the app while on a slow/congested mobile network, spending a fair amount of time as usual checking spelling and wording choice. Then I hit publish, or actually “Publicera” as I’m using the app in Swedish.

I think it was about the same time that I hit publish that I lost data traffic entirely, at least I saw no “bars” right after.

The new toot UI closed but my toot wasn’t published. I don’t recall seeing a error or anything unusual.

### Expected Behavior

If it’s not possible to publish the toot due to network conditions I’d expect the UI to remain open and show some kind of error, so that I can try again later.

If there was an auto-saving drafts feature I’d additionally expect my toot to remain in drafts if I closed the app right after publishing and didn’t notice it didn’t go through.

### Steps To Reproduce

I can’t give reliable steps to reproduce because I can’t control the network around me and am still on the bad network. If at home on WiFi what I’d try is turning off power to the WiFi router and immediately after hit publish, before the phone shows that the network connection has been lost.

If there is no code that tries to handle network issues when posting today then I trust this report is enough to track that. But if there is some code and it should actually work then I’m happy to try reproducing the problem.

### Environment

```markdown
- Device: iPhone 12
- OS: iOS 16.1.1
- Version: v1.4.9
- Build: 224
```

### Anything else?

I toot at https://mastodon.nu/@foolip

**Comment by j-f1** [comment] 2023-01-01 12:16
Related: #482

**Comment by StephanEggermont** [comment] 2023-08-30 08:44
This still shows up as of today. It is not just with bad network, also with high server load

**Comment by StephanEggermont** [comment] 2024-07-09 15:41
Still happening

**Comment by whattherestimefor** [comment] 2024-12-06 21:25
Duplicate of https://github.com/mastodon/mastodon-ios/issues/1215

**Closed as completed by whattherestimefor** 2024-12-06 21:25 UTC
