### ISSUE TITLE
[Bug] Issue when uploading images 

### ISSUE THREAD

**Issue by oliverguhr** [mastodon/mastodon-ios#1063] opened 2023-06-18 10:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I add an existing image to a post, the image selection UI does not close. When I go back to the app, the app is frozen.

### Expected Behavior

The app should add the image to the post. 

### Steps To Reproduce

1. create a new toot
2. Add a image from you library 

### Environment

```markdown
- Device: iPhone 13
- OS: iOS 16.3.1
- Version: 2023.9
- Build: 324
```

### Anything else?

Video https://github.com/mastodon/mastodon-ios/assets/3495355/a0e202a1-71db-4b36-a2f6-a8860e49ba9d

**Comment by zeitschlag** [comment] 2023-06-20 12:21
Duplicate of #965

**Closed as not planned by zeitschlag** 2023-06-20 12:21 UTC
