### ISSUE TITLE
[BUG] Crash before maximum toot lenght is reached

### ISSUE THREAD

**Issue by likethegoddess** [mastodon/mastodon-ios#1345] opened 2024-09-25 23:15 UTC
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

Note: This issue only appears when the display is set to larger text. 

When creating a new post, I can only type a few lines of text before the app freezes entirely. 

![IMG_3603](https://github.com/user-attachments/assets/f13b0433-4cb8-4513-86de-014602706ecf)

### Expected Behavior

I expect to be able to type up to the character limit. 

### Steps To Reproduce

1) Go to Settings > Display & Brightness > Display, and set Display Zoom to Larger Text
2) Launch app and start creating a post

### Environment

```markdown
- Device:iPhone 15
- OS: iOS
- Version: 17.6.1
- Build:
```

**Comment by christianbilodeau** [comment] 2024-09-27 16:00
👋 I had a look at this one by curiosity, there are some logged errors when this screen is shown: `Attempted to access the table view's visibleCells while they were in the process of being updated, which is not allowed.`

Maybe this will help someone: there is a block responsible for updating the cell height when the viewmodel `contentCellFrame` changes. It's accessing the TV `visibleCells` [here](https://github.com/mastodon/mastodon-ios/blob/f1138101238cc25ae894d43a64130e14d1d94765/MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/ComposeContentViewModel%2BDataSource.swift#L42). If the block is commented out, the error log disappears and the app doesn't freeze. I'm not sure about the purpose of the cell height update, I couldn't notice the behavior on my phone 🤔

**Comment by christianbilodeau** [comment] 2024-09-27 16:24
It's the same problem as [this one](https://github.com/mastodon/mastodon-ios/issues/705). 
See [this reply](https://github.com/mastodon/mastodon-ios/issues/705#issuecomment-1363428041) for what I'm referring to in my previous comment.

**Comment by whattherestimefor** [comment] 2024-11-20 14:47
Duplicate of https://github.com/mastodon/mastodon-ios/issues/705

**Closed as completed by whattherestimefor** 2024-11-20 14:47 UTC
Labels: Bug
