### ISSUE TITLE
[BUG] App crash when reaching the max char limit in a post

### ISSUE THREAD

**Issue by abeldotam** [mastodon/mastodon-ios#1185] opened 2023-11-27 11:45 UTC
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

When I type my post and I reach the limit of character, the application will crash.

You can check my post here: https://h4.io/deck/@abel/111479644430425740

Video here (skip to 0:50):
https://github.com/mastodon/mastodon-ios/assets/5216201/d0d27518-ccae-42c2-9fbc-2140abe3ad0e

### Expected Behavior

Not crash, and being able to send my post, or have an error warning saying that I'm off limit

### Steps To Reproduce

In the iOS 17.1.1, with the Mastodon application version 2013.16, try to make a post and reach the limit of char.

I've tested it on my account @abel@h4.io and can still reproduce.

### Environment

```markdown
- Device: iPhone 13 Mini
- OS: iOS 17.1.1
- Version: 2023.16
- Build: 6043
```

**Comment by zeitschlag** [comment] 2024-04-11 14:25
Duplicate of #1255, fixed in 2024.3

**Closed as completed by zeitschlag** 2024-04-11 14:25 UTC
Labels: Bug, Needs Triage
