### ISSUE TITLE
[BUG] Can't refresh 

### ISSUE THREAD

**Issue by rbelew** [mastodon/mastodon-ios#942] opened 2023-02-15 05:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I now have to kill the app (toss it away) and restart it to have the updated state of my instance reflected by the app.  

I think this behavior started w/ the v1.4.11 update

### Expected Behavior

Clicking the home button used to create a spinning disc until I got the purple "New Posts" button.  The home button now seems to have no effect, and I can't get the "New Posts" button by down-dragging the timeline, either.

### Environment

```markdown
- Device: i6
- OS: iOS 15.7.3
- Version:v1.4.11
- Build:265
```

**Comment by Felge-Schneider** [comment] 2023-02-15 12:53
I can confirm this bug on iPhone 13 mini, iOs 16.1.2

**Comment by samadenbaum** [comment] 2023-02-23 13:53
I have the same issue on iPadOS 16.3.1, but not Android 13

**Comment by ghost** [comment] 2023-02-25 16:09
My app refreshes only about 1/5 times when randomly opened. iOS 16.3.1

**Comment by nvsystems** [comment] 2023-02-26 09:16
1.4.12 which was just released has NOT fixed this for me. Refreshing the timeline just does not work.
Opening/closing the app multiple times changes nothing, only force close of the app works.

My guess is that the 1/5 times it works for the previous poster is only when due to memory pressure from using other apps iOS has force closed the mastodon iOS app in the background for him sometimes and then it’s a fresh start.

**Comment by AInteriorB** [comment] 2023-02-28 19:46
Can confirm this bug. Timeline doesn‘t refresh neither after opening the app nor on down-dragging. Current workaround for me is to change the „tab“ (i.g. go to notifications) and then back to home to force a refresh.

**Closed as completed** 2023-03-01 15:41 UTC
Labels: Bug

**Comment by kimar** [comment] 2023-03-01 15:43
Thank you everyone for your input. A fix for this bug will be rolled out shortly.

**Comment by rbelew** [comment] 2023-03-14 17:12
Well done, works for me now!
